version: "3.9"

services:
  seq:
    image: datalust/seq
    ports:
      - 5341:5341
      - 5342:80
    volumes:
      - rps_seq_data:/data
    environment:
      - ACCEPT_EULA=Y

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

game-master:
  build:
    context: .
    dockerfile: GameMasterService/Dockerfile
  image: nitrozeus1/rps-game-master:${DEPLOY_NUMBER}
  depends_on:
    - seq
    - zipkin
    - rmq

  copy-player:
    build:
      context: .
      dockerfile: CopyPlayerService/Dockerfile
    image: nitrozeus1/rps-copy-player:${DEPLOY_NUMBER}
    depends_on:
      - seq
      - zipkin
      - rmq

  random-player:
    build:
      context: .
      dockerfile: RandomPlayerService/Dockerfile
    image: nitrozeus1/rps-random-player:${DEPLOY_NUMBER}
    depends_on:
      - seq
      - zipkin
      - rmq

#  rmq:
#    image: rabbitmq:management
#    ports:
#      - 5672:5672
#      - 15672:15672
#    environment:
#      - RABBITMQ_DEFAULT_USER=application
#      - RABBITMQ_DEFAULT_PASS=pepsi
#    volumes:
#      - rps_rmq_data:/var/lib/rabbitmq

volumes:
  rps_seq_data:
  rps_rmq_data: